trigger:
  - master
  
variables:
  buildConfiguration: 'Release'

pool:
  vmImage: 'windows-latest'
  
steps:
  - task: UseDotNet@2
    displayName: Use .NET 6.0.x
    inputs:
      packageType: 'sdk'
      version: '6.0.x'
      performMultiLevelLookup: true
  - task: DotNetCoreCLI@2
    displayName: Restore Nugets
    inputs:
      command: 'restore'
      feedsToUse: 'select'
      noCache: true
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      arguments: --configuration $(buildConfiguration)
  - task: DotNetCoreCLI@2
    displayName: Run Unit tests
    inputs:
      command: 'test'
      testRunTitle: 'Fides'
      arguments: '--configuration $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: Create and publish packages
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: 'src\**\*.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Fides'
      publishLocation: 'Container'
  