trigger:
  - master
  
pool:
  vmImage: 'windows-latest'
  
steps:
  - task: DotNetCoreCLI@2
    displayName: Restore Nugets
    inputs:
      command: 'restore'
      feedsToUse: 'select'
      noCache: true
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
  - task: DotNetCoreCLI@2
    displayName: Run Unit tests
    inputs:
      command: 'test'
      testRunTitle: 'Fides'
  - task: DotNetCoreCLI@2
    displayName: Publish packages
    inputs:
      command: 'publish'
      publishWebProjects: false
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Fides'
      publishLocation: 'Container'
  