services:
    sql:
        container_name: sql
        image: "mcr.microsoft.com/azure-sql-edge:latest"
        hostname: 'sql'
        ports:
            - "1433:1433"
        environment:
            MSSQL_SA_PASSWORD: $MSSQL_SA_PASSWORD
            ACCEPT_EULA: 1

    redis:
        container_name: redis
        image: "redis/redis-stack:latest"
        ports:
            - "6379:6379"
            - "8001:8001"

    rabbitmq:
        container_name: rabbitmq
        image: "rabbitmq:management"
        ports:
            - "15672:15672"
            - "5672:5672"
        environment:
            RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
            RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS

    elasticsearch:
        container_name: elasticsearch
        image: "elasticsearch:${ELASTIC_VERSION}"
        volumes:
            - ./elk/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
            - elasticsearch:/usr/share/elasticsearch/data:z
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            ES_JAVA_OPTS: -Xms512m -Xmx512m
            ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
        networks:
            - elk

    logstash:
        container_name: logstash
        image: "logstash:${ELASTIC_VERSION}"
        restart: always
        volumes:
            - ./elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
            - ./elk/logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
        ports:
            - "5044:5044"
            - "5001:5000/tcp"
            - "5000:5000/udp"
            - "9600:9600"
        environment:
            LS_JAVA_OPTS: -Xms512m -Xmx512m
            LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
        networks:
            - elk
        depends_on:
            - elasticsearch

    kibana:
        container_name: kibana
        image: "kibana:${ELASTIC_VERSION}"
        volumes:
            - ./elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
        ports:
            - "5601:5601"
        environment:
            KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
        networks:
            - elk
        depends_on:
            - elasticsearch

    sqlpad:
        container_name: sqlpad
        image: sqlpad/sqlpad:latest
        hostname: 'sqlpad'
        ports:
            - '3000:3000'
        environment:
            SQLPAD_ADMIN: $SQLPAD_ADMIN
            SQLPAD_ADMIN_PASSWORD: $SQLPAD_ADMIN_PASSWORD
            SQLPAD_APP_LOG_LEVEL: info
            SQLPAD_WEB_LOG_LEVEL: warn
            SQLPAD_CONNECTIONS__sqlserverdemo__name: SQL Server Demo
            SQLPAD_CONNECTIONS__sqlserverdemo__driver: sqlserver
            SQLPAD_CONNECTIONS__sqlserverdemo__host: sql
            SQLPAD_CONNECTIONS__sqlserverdemo__database: master
            SQLPAD_CONNECTIONS__sqlserverdemo__username: sa
            SQLPAD_CONNECTIONS__sqlserverdemo__password: $MSSQL_SA_PASSWORD
        volumes:
            - sqlpad-volume:/var/lib/sqlpad
        depends_on:
            - sql

networks:
    elk:
        driver: bridge

volumes:
    elasticsearch:
    sqlpad-volume:
