trigger: none

pool:
  vmImage: windows-latest
  
steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Subscription'
    ScriptType: 'FilePath'
    ScriptPath: 'pipelines\deploy-arm.ps1'
    azurePowerShellVersion: 'LatestVersion'