trigger: none

pool:
  vmImage: windows-latest
  
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Subscription'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az container create --resource-group Fides --file ./deployment/containers/template.yaml'
