trigger: none

pool:
  vmImage: windows-latest
  
steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Subscription'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'deployment/deploy-infrastructure.sh'