trigger: none

pool:
  vmImage: windows-latest
  
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Subscription'
    azureContainerRegistry: 'containerregistryfides'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'